### ISSUE TITLE
Missing value

### ISSUE THREAD

**Issue by sakitA** [MicrosoftDocs/OfficeDocs-Exchange#2996] opened 2022-02-22 14:21 UTC
`REPLICATION` value not explained in this https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-logs/message-tracking.md#message-tracking documentation

**Comment by get-itips** [comment] 2022-03-04 21:28
Hello @sakitA 
While I try to reproduce the value in my lab, have you seen _REPLICATION_ as event id or event source?
Thank you

**Comment by sakitA** [comment] 2022-03-05 03:52
Hello @get-itips  yes I saw when using cmdlet to reading mail trace. so that I opened this issue. On Monday I will upload some screen shot for you

**Comment by sakitA** [comment] 2022-03-05 03:55
@get-itips I saw *REPLICATION* as event source

**Comment by get-itips** [comment] 2022-03-22 22:04
@sakitA Sakit, I am having trouble reproducing that exact event source, can you kindly share your associated EventId? Thanks

**Comment by sakitA** [comment] 2022-03-23 08:17
@get-itips sorry for late response. you can see from the below image. to reproduce just send an email and after that just call tracking log cmdlet then you will see the `REPLICATION` on event column

<img width="1242" alt="Screenshot 2022-03-23 091504" src="https://user-images.githubusercontent.com/5094655/159653711-0b396c2f-e466-400e-8b7c-e19e459e2fde.png">

**Comment by get-itips** [comment] 2022-03-23 15:53
@sakitA Thanks for that, is that a DAG environment maybe and is it 2019?

**Comment by get-itips** [comment] 2022-04-13 11:50
Hello @sakitA Sakit, could you see my last comment? Thank you

**Comment by sakitA** [comment] 2022-04-16 14:05
hi @get-itips. Sorry for late response. If you have MS email please reach me over teams or email. satakishiyev@microsoft.com my email address. For you question, to be honest I don't know. I found this issue during my training on February. I just created a test tenant with 3 different users. And then send email from one user to other user. When I trace the email I see that this `REPLICATION` on the source column and not found what this is on the documentation

**Comment by get-itips** [comment] 2022-05-17 12:55
Closing for now as could not reproduce, it can be re-opened in the future.
Thank you!
cc @scanum

**Closed by get-itips** 2022-05-17 12:55 UTC
Labels: doc-bug
