### ISSUE TITLE
Port Test Website Has Expired SSL Certificate

### ISSUE THREAD

**Issue by TotalGriffLock** [MicrosoftDocs/OfficeDocs-Exchange#2053] opened 2020-06-17 08:41 UTC
Your page https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#running-setup talks about downloading a powershell script from https://aka.ms/hybridconnectivity to test connectivity. The script tries connecting to https://aadap-portcheck-seaus.connectorporttest.msappproxy.net:8080 which has an expired SSL certificate. The cmdlet will always fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment] 2020-06-19 04:47
@TotalGriffLock  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment] 2020-06-19 13:54
Duplicate of #1977

**Comment by mattpennathe3rd** [comment] 2020-06-30 22:54
@TotalGriffLock I verified with our technical teams that this test is deprecated and the script will be updated in the next build release. Thanks for reporting this.

**Closed by mattpennathe3rd** 2020-06-30 22:54 UTC
