### ISSUE TITLE
Some cmdlets only run from Exchange Shell, not Remote Session

### ISSUE THREAD

**Issue by justadakaje** [MicrosoftDocs/OfficeDocs-Exchange#764] opened 2019-04-03 21:39 UTC
I spent far too much time today trying to research and figure out why these well-documented commands on multiple Exchange Docs were not working for me and yielding an error. Turns out, cmdlets such as "Get-MailboxDatabase | Get-MailboxStatistics" can only be ran from an Exchange Server in the Shell. I perform nearly every Exchange mgmt task from my own machine via Remote Session. ($ExchSession = New-PSSession.... Import-PSSession $ExchSession...). When I run that command in Remote Session, I receive an error: The specified mailbox "DB15" doesn't exist. [Get-MailboxStatistics], ManagementObjectNotFoundException/.
Solution: Please specify in this document where these commands should or can be ran from. This was new to me. Had this been called out in the documentation, I wouldn't have spent so much time on this. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7806b1-c698-608a-f467-c0bc73a3fdad
* Version Independent ID: 968d86d1-57b6-c3d3-77e6-e21ad5d51071
* Content: [Connect or restore a deleted mailbox: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/connect-or-restore-a-deleted-mailbox-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/connect-or-restore-a-deleted-mailbox-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/connect-or-restore-a-deleted-mailbox-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @dstrome

**Comment by chrisda** [comment] 2019-04-08 19:50
@justadakaje. that idea is new to me, too; it should work in either environment. Perhaps the exception is if there is something unusual about the client machine that you are using to connect? For example, I presume it's in the same domain as the Exchange servers?


Or, there could be an issue pipelining in the remote session? Does Get-MailboxDatabase work by itself? If so, can you run the command:

```
Get-MailboxDatabase | Format-List Name,DistinguishedName,GUID
```

And then run the Get-MailboxStatistics cmdlet with the Database parameter by itself using one of those values as a test?

**Comment by agowa338** [comment] 2019-04-08 20:35
You need to specify the server or the identity with something like "SERVER\*", depending on the command, as they assume you want data about the local host. You get the same behaviour if you execute these commands on a exchangeserver without any database...

**Comment by scanum** [comment] 2019-04-15 21:22
@officedocsbot assign @scanum

**Comment by justadakaje** [comment] 2019-04-15 21:52
Sorry for the reply delay!
@chrisda Yes, both commands, when run separately, work fine via Remote session. Seems to only be an issue when I try to run the example provided in this doc in [THIS](https://docs.microsoft.com/en-us/exchange/connect-or-restore-a-deleted-mailbox-exchange-2013-help#use-the-shell-to-restore-a-deleted-mailbox) section.
@agowa338 My qualm with this is that the Doc doesn't state this "required" param in the Examples. I see what you mean though.

More info:
The specified mailbox "DB01" doesn't exist.
    + CategoryInfo          : NotSpecified: (:) [Get-MailboxStatistics], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : [Server=EXCH01,RequestId=10f7784e-e65a-469d-bb2d-eb9efad19ad6,TimeStamp=4/15/2019 9:47:32 PM] [FailureCategory=Cmdlet-ManagementObjectNotFoundExce
   ption] 5566C12C,Microsoft.Exchange.Management.MapiTasks.GetMailboxStatistics
    + PSComputerName        : exch01

**Comment by justadakaje** [comment] 2019-04-15 22:22
Also, according to the [Online Help article](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/Get-MailboxStatistics?view=exchange-ps) for the Get-MailboxStatistics cmdlet, the `-Database ` parameter does accept input from the pipeline. Further, Example 5 of that article again uses the `Get-MailboxDatabase | Get-MailboxStatistics -Filter 'DisconnectDate -ne $null'` verbiage, which does **not** yield an error via Remote PowerShell. Seems like doing the Filter in-line rather than after the pipeline might be the key?

**Comment by chrisda** [comment] 2019-05-07 18:18
@justadakaje, OK. With your help, I've figured it out. We know that this command:

```
Get-MailboxDatabase | Get-MailboxStatistics | Where {$_.DisconnectReason -eq "Disabled"} | fl DisplayName,MailboxGuid,LegacyDN,Database
``` 

doesn't run in remote PowerShell; it only works in the Exchange Management Shell.

But, I also confirmed that DisconnectReson isn't a filterable property; it errors in Exchange Management Shell or remote PowerShell if you try the command:

```
Get-MailboxStatistics -Filter {DisconnectReason -eq 'Disabled'}
```

After further testing, this is what works for me (in both remote PowerShell and the Exchange Management Shell):

```
$dbs = Get-MailboxDatabase
$dbs | foreach {Get-MailboxStatistics -Database $_.DistinguishedName} | where {$_.DisconnectReason -eq 'Disabled'} | Format-List DisplayName,MailboxGuid,LegacyDN,Database
```

It probably has something to do with how Get-MailboxDatabase takes either a mailbox identity or a database identity, but only the Identity parameter (mailbox identity) is positional (meaning, you don't need to specify the value \-Identity in the command).

Please confirm.

**Comment by scanum** [comment] 2019-06-05 18:18
@justadakaje  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment] 2019-06-05 18:18
@officedocsbot close

**Closed by scanum** 2019-06-05 18:18 UTC
