### ISSUE TITLE
Finalizing Cutover migration 

### ISSUE THREAD

**Issue by harindergiri** [MicrosoftDocs/OfficeDocs-Exchange#1937] opened 2020-04-30 00:13 UTC
Even though Forwarding addresses are not needed when doing a cutover migration from G Suite to Exchange Online. but the status of Migration will be failed and Reports will say Error: TooManyTransientFailureRetriesPermanentException/GmailForwardingAddressRequiresVerificationException: Error: The job encountered too many transient failures ‎(61)‎ and is quitting. The most common failure is GmailForwardingAddressRequiresVerificationException with the hit count 60. --&gt; Can‎'t use forwarding address "****@****.mail.onmicrosoft.com". Gmail requires that forwarding address to be verified. Try a different forwarding address pattern or verify the address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment] 2020-05-01 05:58
@harindergiri  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by sullrich** [comment] 2020-05-27 14:38
I am currently underway with a migration and stuck against this issue.  Can anyone outline what is needed to prevent the failure.  I do not need forwarding as we cut the MX before migration.

**Comment by harindergiri** [comment] 2020-05-28 03:31
Hi @sullrich  
This is a cosmetic issue  just make sure your mailbox are fully synced and do the cutover , even though result will say failed but it will be all good , failure is just for the forward

**Comment by Antonija555** [comment] 2020-10-20 13:52
Any news on this issue?

**Comment by wrall** [comment] 2020-12-16 09:25
This is by design.  The "Perform a G Suite Migration" article discusses a staged migration process from G Suite involving supporting mail routing between the two environments.  For a cutover migration, the steps would be changed in the following way:
- No need to perform the [Create a sub-domain for mail routing to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-microsoft-365-or-office-365) or [Create a sub-domain for mail routing to your G Suite domain](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-your-g-suite-domain) steps.
- During the [Provision users in Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#provision-users-in-microsoft-365-or-office-365) step, the users should instead be provisioned as Mailboxes instead of MailUsers with no need to set ExternalEmailAddress or add any proxy address for the routing domains.
- There is no need to perform the Complete action.  Instead, the batch should remain in Synced state, and then removed after the MX record has been updated and all of the users have started using the new system.  The TargetDeliveryDomain would not be relevant for this migration.
 
The Completion phase is for Staged migrations, and all that it does is set the forwarding address on the G Suite side, clear any forwarding address on the O365 side, and run an additional incremental sync of changes after that has been done.

**Comment by dariomws** [comment] 2020-12-17 19:52
@scanum this was answered by @wrall, I think you can close it.

Thanks to everyone for your feedback!

**Comment by scanum** [comment] 2021-01-07 02:47
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Closed by scanum** 2021-01-07 02:47 UTC
