### ISSUE TITLE
Download link https://www.microsoft.com/download/details.aspx?id=29567 for  "MONTI application and accompanying documentation" returns 404

### ISSUE THREAD

**Issue by jinzheng-msft** [MicrosoftDocs/OfficeDocs-Exchange#2668] opened 2021-07-02 05:42 UTC
Hi, the download link https://www.microsoft.com/download/details.aspx?id=29567 for  "MONTI application and accompanying documentation" is no longer valid. When trying to download, it returns 404. Can you please check where the documentation is and link it to the correct URL? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce990e27-aa35-1c80-2d57-c07df2d35e88
* Version Independent ID: 78594f8e-6f98-21bd-4c68-be4facfade3e
* Content: [Migrate from Lotus Notes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-from-lotus-notes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment] 2021-07-05 18:57
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2647

**Comment by JoanneHendrickson** [comment] 2021-08-13 15:55
this has been fixed.

**Closed by JoanneHendrickson** 2021-08-13 15:55 UTC
Labels: doc-enhancement
