### ISSUE TITLE
Dependent repositories are not aviable

### ISSUE THREAD

**Issue by valtalion** [MicrosoftDocs/OfficeDocs-Exchange#129] opened 2018-09-26 10:26 UTC
File .openpublishing.publish.config.json contains dependent repositories, but this reposotories are not aviable. For example, 
"dependent_repositories": [
    {
      "path_to_root": "_themes",
      "url": "https://github.com/Microsoft/templates.docs.msft",
      "branch": "master",
      "branch_mapping": {}
    },

but for url https://github.com/Microsoft/templates.docs.msft
![image](https://user-images.githubusercontent.com/43604218/46074218-5b91a580-c1a0-11e8-8f4c-c7a05ede0177.png)

**Comment by AndreaBarr** [comment] 2018-09-26 19:07
@valtalion Thank you for this feedback

It looks like Chris updated the article to address your issue. I am going to close this issue. If the issue is not resolved please reopen.

**Closed by AndreaBarr** 2018-09-26 19:07 UTC
