### ISSUE TITLE
On "How retention age is calculated": typo/error in first example

### ISSUE THREAD

**Issue by wushujames** [MicrosoftDocs/OfficeDocs-Exchange#1672] opened 2020-01-27 06:52 UTC
The first example says:

> Processes the message in the Inbox on 1/26/2019, stamps it with a start date of 01/26/2019 and an expiration date of 01/26/2014

Where did the "2014" come from? Is that a typo?

Also, should the "expiration" date be "01/26/2020", since the Inbox retention tags says "Delete in 365 days"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a659b815-705f-fa0f-9867-db506cc2c474
* Version Independent ID: d85dba9c-c8d1-7d31-2af3-1a26a13c713f
* Content: [How retention age is calculated](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/retention-age?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/retention-age.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/retention-age.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment] 2020-02-12 21:41
@wushujames Look like this one is a dupe of #1673. Thanks again for proposing the fix.

**Closed by mattpennathe3rd** 2020-02-12 21:41 UTC
