### ISSUE TITLE
Needs outbound connectivity requirements

### ISSUE THREAD

**Issue by mramnet** [MicrosoftDocs/OfficeDocs-Exchange#1584] opened 2019-12-09 08:42 UTC
Article lists inbound connectivity but not outbound connectivity requirements for installation of the HCW.  Locked environments need this explicitly listed or well understood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/Exchange/hybrid-deployment-prerequisites#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment] 2020-04-12 03:27
@mramnet This is a duplicate of #1559 and I am actively working to get more information on that issue, so I will close your issue now, but please follow along on the other issue if you wish.

**Closed by mattpennathe3rd** 2020-04-12 03:27 UTC
