### ISSUE TITLE
PowerShell and Exchange Online

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-Exchange#327] opened 2018-11-21 19:24 UTC
I believe there's a misstatement in the "Authentication policy procedures in Exchange Online" section. It states:

"Used to connect to Exchange Online with remote PowerShell. If you block Basic authentication for Exchange Online PowerShell, you need to use the Exchange Online PowerShell Module to connect. "

However, the traditional way of connecting to Exchange Online with PowerShell continues to work once set to basic auth (completely set--no exception for PowerShell).

Could it be that you actually meant this: If you block Basic authentication, *and you use MFA*, then you need to use the Exchange Online PowerShell Module to connect.

In other words, if you're not using MFA, there's nothing to change even if on basic auth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online?redirectSourcePath=%252fen-us%252farticle%252fdisable-basic-authentication-in-exchange-online-bba2059a-7242-41d0-bb3f-baaf7ec1abd7)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Product: **office-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment] 2018-11-21 22:42
@rpodric I confirmed that the way the topic is written is the expected behavior (if you block Basic auth for PowerShell, you'll need to use MFA and the Exchange Online PowerShell Module). As described in the topic, the policies don't take effect immediately (up to 24 hours), so it is possibly you're still able to connect to Exchange Online PowerShell 'the regular way' because the 'block Basic auth' policy hasn't taken effect yet?.

**Comment by rpodric** [comment] 2018-11-21 22:56
Very interesting. I'll report back if that's the case, but I did use this afterwards:

Set-User -Identity "user@contoso.com" -STSRefreshTokensValidFrom $([System.DateTime]::UtcNow)

**Comment by toledotown** [comment] 2018-12-03 20:20
I have disabled all basic auth for a week and can still connect using the traditional method.

**Comment by leroybarnes** [comment] 2018-12-12 21:16
How do I see what users are assigned to an authorization policy?

**Comment by rdiazel** [comment] 2019-02-07 02:21
@leroybarnes To confirm that the authentication policy was applied to users:
Run the following command to find the distinguished name (DN) value of the authentication policy:
Get-AuthenticationPolicy | Format-List Name,DistinguishedName
Use the DN value of the authentication policy in the following command:
Get-User -Filter {AuthenticationPolicy -eq '<AuthPolicyDN>'}

**Comment by scanum** [comment] 2019-05-07 00:46
@rpodric Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment] 2019-05-07 00:46
@officedocsbot close

**Closed by scanum** 2019-05-07 00:46 UTC
